### ISSUE TITLE
Request for clarification regarding dc:creator

### ISSUE THREAD

**Issue by johnjung** [johnjung/metadata_converters#10]
The spec says to pull dc:creator from the marc 100 field. Please confirm: should subfields a-z be concatenated together for one dc:creator per 100 field, or should I just use subfield a?

**Comment by dbietila** [comment]
Please bring in 100, 110, or 111 for creator. Bring in any alpha subfields (|a, |b, etc.), but not numeric subfields.

**Comment by johnjung** [comment]
@dbietila, the [base transform includes a line that brings in a 245c for creator as well](https://github.com/johnjung/metadata_converters/blob/ad51d8747c088a6e05efb10ca7fc0860fc4c7dad/metadata_converters/classes.py#L107). Should this be removed?

**Comment by johnjung** [comment]
Folded this issue into https://github.com/johnjung/metadata_converters/issues/13. Closing this out.
