### ISSUE TITLE
Request for clarification regarding dc:identifiers

### ISSUE THREAD

**Issue by johnjung** [johnjung/metadata_converters#11]
[This record](https://catalog.lib.uchicago.edu/vufind/Record/1595409/Details#tabnav) contains several 856's with a subfield u. Should each one produce a separate dc:identifier, or should these be summarized by a single identifier? If they should be combined, what should that identifier be?

**Comment by dbietila** [comment]
I would just ignore that record. It's like an aggregate record for a portion of the whole map series. There are individual bib records for all of those maps, though, which are better for our purposes.

**Comment by johnjung** [comment]
[Added a comment to document this](https://github.com/johnjung/metadata_converters/blob/946da408576685e6a4fea78a7b55f7a5017f9989/xslt/socscimaps_dc.xslt#L7). Closing this issue out.
