### ISSUE TITLE
Mismatch between spec and place types in database output

### ISSUE THREAD

**Issue by johnjung** [johnjung/metadata_converters#15]
The [MEPA metadata template spec](https://docs.google.com/document/d/1Nrh31iFaqHX2rwFWF7lNA-2u6Ib2tXOpIUir6GP50DQ/edit) lists the following place-related predicates for a CHO:

vra:Continent "[FMField:Continent]"; 
vra:Country "[FMField:Country]";
vra:State "[FMField:State/Region]";
vra:City "[FMField:City or County]";
vra:Place "[FMField:Site OR Building]";

This doesn't quite line up with what I'm getting from work elements in the VRACore output from filemaker:

&lt;location type="creation"&gt;
  &lt;name type="geographic" vocab="TGN" refid="7001188" extent="inhabited place"&gt;Alexandria&lt;/name&gt;
  &lt;name type="geographic" vocab="TGN" refid="7001413" extent="region"&gt;Urban&lt;/name&gt;
  &lt;name type="geographic" vocab="TGN" refid="7016833" extent="nation"&gt;Egypt&lt;/name&gt;
  &lt;name type="geographic" vocab="TGN" refid="7001242&#10;" extent="continent"&gt;Africa&lt;/name&gt;
&lt;/location&gt;

&lt;location type="creation"&gt;
  &lt;name type="geographic" vocab="TGN" refid="7002543" extent="inhabited place"&gt;İzmir&lt;/name&gt;
  &lt;name type="geographic" vocab="TGN" refid="1001053" extent="province"&gt;İzmir&lt;/name&gt;
  &lt;name type="geographic" vocab="TGN" refid="1000144" extent="nation"&gt;Turkey&lt;/name&gt;
  &lt;name type="geographic" vocab="TGN" refid="1000004" extent="continent"&gt;Asia&lt;/name&gt;
&lt;/location&gt;

Sample data records all contain continents and nations. Some contain provinces. All contain "inhabited places", and none seem to contain sites or buildings. The data contains references to "regions", which don't appear in the output. 

I assume we should omit triples for province/state and site or building where they don't occur in the data. Should I map inhabited place to City or County, in our output?

**Comment by dbietila** [comment]
I would map "inhabited place" to vra:City.

I'm confused about "region" not appearing in the output. Don't you cite this line? 
type="geographic" vocab="TGN" refid="7001413" extent="region">Urban

**Comment by dbietila** [comment]
Regarding sites or buildings, I seem to recall that only a few records had this field populated. Thomas may be able to help identify these.

You are correct that we can omit triples when there is no relevant data.

**Comment by johnjung** [comment]
Sounds good. Regarding "region"- that doesn't seem to make sense as a continent, country, state or city. In the spec "place" seems to be used to describe very precise locations. Should I just omit region?

**Comment by johnjung** [comment]
Mapping TGN.province and TGN.region to VRA.state.
