### ISSUE TITLE
DC converter for MEPA?

### ISSUE THREAD

**Issue by johnjung** [johnjung/metadata_converters#17]
Is it useful to have a separate VRACore to DC converter, analogous to the MARC to DC converter for the social scientists maps? (the [spec](https://docs.google.com/document/d/1Nrh31iFaqHX2rwFWF7lNA-2u6Ib2tXOpIUir6GP50DQ/edit) contains a reference to the MARC to DC converter.)

**Comment by dbietila** [comment]
Speculum also contains VRA content, but I'm not aware of other local collections that use it. We may want to do some analysis of how similarly VRA is used in MEPA and Speculum, to inform any decision on whether a VRA to DC converter will be worthwhile.

**Comment by johnjung** [comment]
Ok- if DC metadata doesn't need to exist separately, I'm going to save this as a potential enhancement when we do the speculum EDM.
