### ISSUE TITLE
regularize use of rights/licenses? 

### ISSUE THREAD

**Issue by johnjung** [johnjung/metadata_converters#21]
In the [MEPA spec](https://docs.google.com/document/d/1Nrh31iFaqHX2rwFWF7lNA-2u6Ib2tXOpIUir6GP50DQ/edit), work level or recto verso level cultural heritage objects, resource maps and aggregations use a mix of dc:rights or edm:rights predicates with a mix of the following licenses:

http://creativecommons.org/licenses/by/4.0/
http://creativecommons.org/licenses/by-nc/4.0/
http://creativecommons.org/licenses/by-sa/4.0/

This differs from the way rights are assigned in the [Maps spec](https://docs.google.com/document/d/11QaNUMEtjp9DMkwkttvm1zMFF6rV1KrfVe2SYr1brVA/edit).

Are the way rights are expressed in these specs correct?

**Comment by johnjung** [comment]
As per Charles, I'm including edm:rights on aggregations and dc:rights on cultural heritage objects. 

The edm:rights elements should include a URI, e.g. https://creativecommons.org/licenses/by/4.0/. There are still several licenses in use in MEPA, and a different license appears in the Maps spec. Please let me know which license or licenses are appropriate, and if they should be used for both the maps and MEPA project or if the licenses on the two projects should differ.

**Comment by dbietila** [comment]
https://creativecommons.org/licenses/

**Comment by johnjung** [comment]
As per our meeting with DB, TD and CB, use BY-SA for the time being.
